name: tedy_cli
description: tedy-cli is a simple cli written in dart & code generator used with flutter.
version: 1.0.0
author: Islam Emad <Islam-Emad@outlook.com>
homepage: https://github.com/Eslam-Emad/tedy-cli

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
